# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Base URL
# baseurl:          /fantastiq
baseurl:          ''

# Setup
title:            '@nazrulhisham_'
tagline:          'Everlasting Harmony & Serenity'
description:      'Rakyat marhaen. Bejiwa besar, bercita-cita tinggi tapi tak tahan godaan. Pandai menghormati orang yang lebih tua. Sedikit mata duitan. Suka makan. Paling getik layan kebodohan orang dan benci buang masa.'
url:              http://hello.nazrulhisham.net
paginate:         4
author:
  name:           'Nazrul Hisham'
  url:            https://twitter.com/nazrulhisham_

# Custom vars
version:          0.0.2

github:
  repo:           https://github.com/lumachroma/fantastiq
