# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Base URL
# baseurl:          /fantastiq
baseurl:          ''

# Setup
title:            '@nazrulhisham_'
tagline:          'Everlasting Harmony & Serenity'
description:      'Rakyat marhaen. Bejiwa besar, bercita-cita tinggi tapi tak tahan godaan. Pandai menghormati orang yang lebih tua. Sedikit mata duitan. Suka makan. Paling getik layan kebodohan orang dan benci buang masa.<p>[<a href="http://t.co/e8B29HCP" target="_blank">fb</a>] [<a href="http://t.co/liyroSof" target="_blank">tw</a>] [<a href="http://t.co/wZ3EhfO0" target="_blank">ig</a>]</p>'
url:              http://hello.nazrulhisham.net/
paginate:         3
author:
  name:           'Nazrul Hisham'
  url:            https://twitter.com/nazrulhisham_

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/lumachroma/fantastiq
